#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Pre-commit for client

cd ./client
yarn lint-staged
yarn test:badges
git add ./badges
cd ..

# Pre-commit for server

cd ./server
yarn lint-staged
yarn test:badges
git add ./badges
cd ..