name: CI & CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.9.0

      - name: CLIENT - Install dependencies and run tests
        run: |
          cd ./client
          yarn install
          yarn test
          cd ..

      - name: SERVER - Install dependencies and run tests
        run: |
          cd ./server
          yarn install
          yarn test
          cd ..
  deploy:
    needs: build
    
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install and build
        run: |
          cd ./client
          yarn install
          yarn build
          cd ..
          cd ./server
          yarn install --ignore-scripts
          yarn build
          cd ..

      - name: Heroku deployment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true