name: CI & CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and run tests
        env:
          PORT: ${{ secrets.PORT }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DB_URL_PROD: ${{ secrets.DB_URL_PROD }}
          DB_URL_DEV: ${{ secrets.DB_URL_DEV }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          IMGUR_ID: ${{ secrets.IMGUR_ID }}
          IMGUR_SECRET: ${{ secrets.IMGUR_SECRET }}
          IMGUR_ALBUM: ${{ secrets.IMGUR_ALBUM }}
          IMGUR_TOKEN:  ${{ secrets.IMGUR_TOKEN }}
        run: |
          yarn install
          yarn test

  deploy:
    needs: build
    
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Heroku deployment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}